export const ADD_TODO = 'POST/ADD_TODO'
export const DELETE_TODO = 'POST/DELETE_TODO'
export const EDIT_TODO = 'POST/EDIT_TODO'
export const SHOW_ALERT = 'ALERT/SHOW_ALERT'
export const HIDE_ALERT = 'ALERT/HIDE_ALERT'